/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UudisedRouteImport } from './routes/uudised'
import { Route as TehtudToodRouteImport } from './routes/tehtud-tood'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UudisedIndexRouteImport } from './routes/uudised/index'
import { Route as UudisedSlugRouteImport } from './routes/uudised/$slug'

const UudisedRoute = UudisedRouteImport.update({
  id: '/uudised',
  path: '/uudised',
  getParentRoute: () => rootRouteImport,
} as any)
const TehtudToodRoute = TehtudToodRouteImport.update({
  id: '/tehtud-tood',
  path: '/tehtud-tood',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UudisedIndexRoute = UudisedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UudisedRoute,
} as any)
const UudisedSlugRoute = UudisedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UudisedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tehtud-tood': typeof TehtudToodRoute
  '/uudised': typeof UudisedRouteWithChildren
  '/uudised/$slug': typeof UudisedSlugRoute
  '/uudised/': typeof UudisedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tehtud-tood': typeof TehtudToodRoute
  '/uudised/$slug': typeof UudisedSlugRoute
  '/uudised': typeof UudisedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tehtud-tood': typeof TehtudToodRoute
  '/uudised': typeof UudisedRouteWithChildren
  '/uudised/$slug': typeof UudisedSlugRoute
  '/uudised/': typeof UudisedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tehtud-tood' | '/uudised' | '/uudised/$slug' | '/uudised/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tehtud-tood' | '/uudised/$slug' | '/uudised'
  id:
    | '__root__'
    | '/'
    | '/tehtud-tood'
    | '/uudised'
    | '/uudised/$slug'
    | '/uudised/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TehtudToodRoute: typeof TehtudToodRoute
  UudisedRoute: typeof UudisedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uudised': {
      id: '/uudised'
      path: '/uudised'
      fullPath: '/uudised'
      preLoaderRoute: typeof UudisedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tehtud-tood': {
      id: '/tehtud-tood'
      path: '/tehtud-tood'
      fullPath: '/tehtud-tood'
      preLoaderRoute: typeof TehtudToodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uudised/': {
      id: '/uudised/'
      path: '/'
      fullPath: '/uudised/'
      preLoaderRoute: typeof UudisedIndexRouteImport
      parentRoute: typeof UudisedRoute
    }
    '/uudised/$slug': {
      id: '/uudised/$slug'
      path: '/$slug'
      fullPath: '/uudised/$slug'
      preLoaderRoute: typeof UudisedSlugRouteImport
      parentRoute: typeof UudisedRoute
    }
  }
}

interface UudisedRouteChildren {
  UudisedSlugRoute: typeof UudisedSlugRoute
  UudisedIndexRoute: typeof UudisedIndexRoute
}

const UudisedRouteChildren: UudisedRouteChildren = {
  UudisedSlugRoute: UudisedSlugRoute,
  UudisedIndexRoute: UudisedIndexRoute,
}

const UudisedRouteWithChildren =
  UudisedRoute._addFileChildren(UudisedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TehtudToodRoute: TehtudToodRoute,
  UudisedRoute: UudisedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
